export const categories = [
  'All Categories',
  'Science and Technology',
  'Telegram',
  'Work and Career',
  'Pics and Photos',
  'Cryptocurrencies',
  'Cinema & TV',
  '18+',
  'Marketing',
  'Entertainment',
  'Culture and Art',
  'Blogging',
  'Games & Apps',
  'News & Media',
  'Tourism',
  'Policy',
  'Design',
  'Fashion & beauty',
  'Health & Sport',
  'Music',
  'Bussines & Startups',
  'Food & Cooking',
  'Auto & Moto',
  'Other'
];
