export const getLocalizedCategories = intl => [
  { label: intl.messages["category.all"], value: 0 },
  { label: intl.messages["category.science"], value: 1 },
  { label: intl.messages["category.telegram"], value: 2 },
  { label: intl.messages["category.crypto"], value: 3 },
  { label: intl.messages["category.cars"], value: 4 },
  { label: intl.messages["category.business"], value: 5 },
  { label: intl.messages["category.blogging"], value: 6 },
  { label: intl.messages["category.porn"], value: 7 },
  { label: intl.messages["category.health"], value: 8 },
  { label: intl.messages["category.games"], value: 9 },
  { label: intl.messages["category.pictures"], value: 10 },
  { label: intl.messages["category.cinema"], value: 11 },
  { label: intl.messages["category.culture"], value: 12 },
  { label: intl.messages["category.fashion"], value: 13 },
  { label: intl.messages["category.music"], value: 14 },
  { label: intl.messages["category.news"], value: 15 },
  { label: intl.messages["category.education"], value: 16 },
  { label: intl.messages["category.politics"], value: 17 },
  { label: intl.messages["category.tourism"], value: 18 },
  { label: intl.messages["category.work"], value: 19 },
  { label: intl.messages["category.marketing"], value: 20 },
  { label: intl.messages["category.quotes"], value: 21 },
  { label: intl.messages["category.entertainment"], value: 22 },
  { label: intl.messages["category.design"], value: 23 },
  { label: intl.messages["category.food"], value: 24 },
  { label: intl.messages["category.other"], value: 25 },
];